### ISSUE TITLE
Mapping folder with survey.tsv to /data

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/survey-generator#10]
Hi, I'm trying to get a bit more familiar with Expfactory and so was attempting to generate my own survey following [these instructions](https://github.com/expfactory/survey-generator).

I created the required `config.json` and `survey.tsv` files in a local folder and attempted to run:

```zsh
$ docker run -v $PWD:/data expfactory/survey-generator start
```

This gave the error:

```zsh
You must map the folder with your survey.tsv to /data
```

Which seems to be referred to by the note in the directions:

>we map the `$PWD` (or where our survey and config are) to `/data` in the container

However, I am not sure how we do this mapping? Is there any guidance on this?

Thanks!

**Comment by vsoch** [comment]
Try running that same command but instead list files at /data to see if it's there. Either of these will probably do the trick:

```bash
docker run -it -v $PWD:/data --entrypoint bash expfactory/survey-generator ls /data
docker run -it -v $PWD:/data --entrypoint ls expfactory/survey-generator /data
```

**Comment by vsoch** [comment]
Sometimes with environment variable binds, if you don't add the ending slash (e.g., `$PWD/`) it treats it as a named volume. So you could try adding that.

**Comment by danieljwilson** [comment]
Thanks for quick reply!

Running:
```zsh
docker run -it -v $PWD:/data --entrypoint bash expfactory/survey-generator ls /data
```
gave:
```zsh
docker run -it -v $PWD:/data --entrypoint bash expfactory/survey-generator ls /data
```
Running:
```zsh
docker run -it -v $PWD:/data --entrypoint ls expfactory/survey-generator /data
```
gave:
```zsh
config.json  survey.tsv
```
Which seems to have solved the problem...thanks!

**Comment by vsoch** [comment]
Sure thing!
