### ISSUE TITLE
UnicodeEncodeError: '\u2019'

### ISSUE THREAD

**Issue by danieljwilson** [expfactory/survey-generator#11]
So my current workflow is creating the survey item's in Google sheets and then exporting a `.tsv` file.

When running:
```zsh
docker run -v $PWD:/data expfactory/survey-generator start
```

I got the following error:
```zsh
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 0: ordinal not in range(128)
```

And the process stopped at that point (halfway through creating the `.html` file).

This seems to be for the Unicode right quote character - which does appear in the `.tsv` file as a contraction is used for one item. Just wondering if I need to remove or be replacing those with the ASCII equivalent before running?

**Comment by vsoch** [comment]
That's a right single quotation mark - can you not just change it to `"`? That would be the easiest thing to do.

**Comment by danieljwilson** [comment]
I just changed it from `can't` to `cannot` which fixed things.

But then realized that it also works with an actual apostrophe..so just need to make sure when I am copy pasting that apostrophes are not actually right single quotation marks...not always obvious :)
