### ISSUE TITLE
Numeric fields only allow integer values

### ISSUE THREAD

**Issue by earcanal** [expfactory/survey-generator#2]
Field type `numeric` should allow real numbers.  Currently, form validation prevents real values.  You can work around this using `textfield` but you this required careful instructions for completing the field, to avoid people entering values in words e.g. `a half` rather than `0.5`.

**Comment by vsoch** [comment]
Can you give me an example to test this?

**Comment by vsoch** [comment]
It looks like we call the function "create_numeric_textfield" and the outcome should be this:

https://github.com/expfactory/survey-generator/blob/master/survey.py#L239

Is it the case that that output isn't there, or that output doesn't work as it should?

**Comment by earcanal** [comment]
Doesn't work they way I'd' like it to.  I think the problem is that the built-in MDL validation for `type="number"` is integer.  There may not be any real number validation in MDL?* A slightly better workaround than the one above might be to use [`textfield` with a real number regex](https://webdesign.tutsplus.com/tutorials/learning-material-design-lite-text-fields--cms-24614).  So maybe a patch to `survey.py` that adds a new `real` type that generates something like

```
<div class="mdl-textfield mdl-js-textfield">
<input class="mdl-textfield__input page2 required" name="survey_4" type="text" pattern="(([0-9]+)(\.[0-9]+)?)|\.?[0-9]+" id="survey_4" meta-text="Your question text?">
<label class="mdl-textfield__label" for="survey_4"></label>
<span class="mdl-textfield__error">Please enter a real number.</span>
</div>
```

I'll probably scratch my current itch by hacking `index.html` as per the above, and try to avoid this manual fix by regenerating the survey.

*  Incidentally, it looks like MDL is no longer supported.

**Comment by vsoch** [comment]
I can try that change with a PR, and you want to see if it works?

What do you mean it's no longer supported? Wouldn't the style/js sheets be enough?

**Comment by earcanal** [comment]
That would be great.  I've pushed [an example index.html](https://github.com/earcanal/meditation-expertise/commit/fb7cfc7f840e6875e5cbb7907457495171f05f38).

[Material Design Lite is now in limited support ... ](https://github.com/google/material-design-lite).

**Comment by vsoch** [comment]
@earcanal see https://github.com/expfactory/survey-generator/pull/3
